services:
  tarn:
    image: josiahdc/tarn:0.1
    build:
      context: .
    ports:
      - 33322:33333
    networks:
      - ratatosk_ratatosk
    environment:
      STORAGE_DIRECTORY: /atelier/storage
    volumes:
      - /tmp/tarn:/atelier/storage
    env_file:
      - tarn.env

networks:
  ratatosk_ratatosk:
    external: true